name: Lint Code

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint HTML
      run: npm run lint:html

    - name: Lint CSS
      run: npm run lint:css

    - name: Lint JavaScript
      run: npm run lint:js

    - name: Check formatting
      run: npm run format:check